DROP TABLE IF EXISTS all_questions;
CREATE TABLE all_questions(
	QuestionID INT,
	QuestionText VARCHAR(255),
	GroupName VARCHAR(255),
	IsClosed BOOLEAN
);
INSERT INTO all_questions VALUES (1,'Sample Source','NULL',TRUE);
INSERT INTO all_questions VALUES (2,'Age','NULL',TRUE);
INSERT INTO all_questions VALUES (3,'Gender','NULL',TRUE);
INSERT INTO all_questions VALUES (4,'Relationship Status','NULL',TRUE);
INSERT INTO all_questions VALUES (5,'Household','NULL',TRUE);
INSERT INTO all_questions VALUES (6,'Income','NULL',TRUE);
INSERT INTO all_questions VALUES (7,'Investable assets','NULL',TRUE);
INSERT INTO all_questions VALUES (8,'Primary Income Earner Occupation','NULL',TRUE);
INSERT INTO all_questions VALUES (9,'Primary Income Earner Sector','NULL',TRUE);
INSERT INTO all_questions VALUES (10,'Pension Decisions','NULL',TRUE);
INSERT INTO all_questions VALUES (11,'Pension Type','NULL',TRUE);
INSERT INTO all_questions VALUES (12,'Knowledge','NULL',TRUE);
INSERT INTO all_questions VALUES (13,'Other Financial Holdings','NULL',TRUE);
INSERT INTO all_questions VALUES (14,'Estimated total value - ISA','NULL',FALSE);
INSERT INTO all_questions VALUES (15,'Estimated total value - Property','NULL',FALSE);
INSERT INTO all_questions VALUES (16,'Estimated total value - Cash','NULL',FALSE);
INSERT INTO all_questions VALUES (17,'Estimated total value - Inheritance','NULL',FALSE);
INSERT INTO all_questions VALUES (18,'Estimated total value - Other investments','NULL',FALSE);
INSERT INTO all_questions VALUES (19,'Estimated total value - Don''t know / Prefer not to answer','NULL',TRUE);
INSERT INTO all_questions VALUES (20,'Financial Sophistication','NULL',FALSE);
INSERT INTO all_questions VALUES (21,'Regularly check in media','Financial Sophistication',TRUE);
INSERT INTO all_questions VALUES (22,'Confident handling own finances','Financial Sophistication',TRUE);
INSERT INTO all_questions VALUES (23,'Knowledgeable about finances','Financial Sophistication',TRUE);
INSERT INTO all_questions VALUES (24,'Financial Sophistication Classification','NULL',FALSE);
INSERT INTO all_questions VALUES (25,'Low Financial Sophistication','Financial Sophistication Classification',FALSE);
INSERT INTO all_questions VALUES (26,'Medium Financial Sophistication','Financial Sophistication Classification',FALSE);
INSERT INTO all_questions VALUES (27,'High Financial Sophistication','Financial Sophistication Classification',FALSE);
INSERT INTO all_questions VALUES (28,'Interest level','NULL',TRUE);
INSERT INTO all_questions VALUES (29,'Current Value','NULL',TRUE);
INSERT INTO all_questions VALUES (30,'Annual Income','NULL',TRUE);
INSERT INTO all_questions VALUES (31,'Annual Income Value','NULL',TRUE);
INSERT INTO all_questions VALUES (32,'Retirement Age','NULL',TRUE);
INSERT INTO all_questions VALUES (33,'Plans for Retirement','NULL',TRUE);
INSERT INTO all_questions VALUES (34,'Secure in Retirement','NULL',TRUE);
INSERT INTO all_questions VALUES (35,'Taking Advice','NULL',FALSE);
INSERT INTO all_questions VALUES (36,'During career','Taking Advice',TRUE);
INSERT INTO all_questions VALUES (37,'Approaching retirement','Taking Advice',TRUE);
INSERT INTO all_questions VALUES (38,'At retirement','Taking Advice',TRUE);
INSERT INTO all_questions VALUES (39,'During retirement','Taking Advice',TRUE);
INSERT INTO all_questions VALUES (40,'Advice Driver','NULL',TRUE);
INSERT INTO all_questions VALUES (41,'Advice First Stop','NULL',TRUE);
INSERT INTO all_questions VALUES (42,'Pension General Consideration','NULL',TRUE);
INSERT INTO all_questions VALUES (43,'Pension Most Likely Consideration','NULL',TRUE);
INSERT INTO all_questions VALUES (44,'Fees Importance','NULL',TRUE);
INSERT INTO all_questions VALUES (45,'Financial Advisor','NULL',TRUE);
INSERT INTO all_questions VALUES (46,'Advisor Reliance','NULL',TRUE);
INSERT INTO all_questions VALUES (47,'Advice Type','NULL',TRUE);
INSERT INTO all_questions VALUES (48,'Advisor Value','NULL',TRUE);
INSERT INTO all_questions VALUES (49,'No Advisor','NULL',TRUE);
INSERT INTO all_questions VALUES (50,'Advisor Consideration','NULL',TRUE);
INSERT INTO all_questions VALUES (51,'Advisor Qualities','NULL',TRUE);
INSERT INTO all_questions VALUES (52,'Advice Frequency','NULL',TRUE);
INSERT INTO all_questions VALUES (53,'Specialist Type','NULL',TRUE);
INSERT INTO all_questions VALUES (54,'Combining Generations','NULL',TRUE);
INSERT INTO all_questions VALUES (55,'Views on Retirement','NULL',TRUE);
INSERT INTO all_questions VALUES (56,'Retirement Goals','NULL',FALSE);
INSERT INTO all_questions VALUES (57,'Financial Security','Retirement Goals',TRUE);
INSERT INTO all_questions VALUES (58,'Better standard of life','Retirement Goals',TRUE);
INSERT INTO all_questions VALUES (59,'Maintain standard','Retirement Goals',TRUE);
INSERT INTO all_questions VALUES (60,'Experience new things','Retirement Goals',TRUE);
INSERT INTO all_questions VALUES (61,'Not be a burden on my family','Retirement Goals',TRUE);
INSERT INTO all_questions VALUES (62,'Financial Goals','NULL',FALSE);
INSERT INTO all_questions VALUES (63,'More disposable income','Financial Goals',TRUE);
INSERT INTO all_questions VALUES (64,'Enough to live on without budget','Financial Goals',TRUE);
INSERT INTO all_questions VALUES (65,'Enough to last my life','Financial Goals',TRUE);
INSERT INTO all_questions VALUES (66,'Support younger generation','Financial Goals',TRUE);
INSERT INTO all_questions VALUES (67,'Leave inheritance','Financial Goals',TRUE);
INSERT INTO all_questions VALUES (68,'Provision','Financial Goals',TRUE);
INSERT INTO all_questions VALUES (69,'Pension Provision','NULL',FALSE);
INSERT INTO all_questions VALUES (70,'A lot of interest','Pension Provision',TRUE);
INSERT INTO all_questions VALUES (71,'Only think about pension when sending annual statement','Pension Provision',TRUE);
INSERT INTO all_questions VALUES (72,'Confident pension will support retirement','Pension Provision',TRUE);
INSERT INTO all_questions VALUES (73,'Unaware of pension I don’t really know how much money I need to have in my pot','Pension Provision',TRUE);
INSERT INTO all_questions VALUES (74,'Good understanding of process','Pension Provision',TRUE);
INSERT INTO all_questions VALUES (75,'Take advice on legislative changes','Pension Provision',TRUE);
INSERT INTO all_questions VALUES (76,'Importance of flexibility','Pension Provision',TRUE);
INSERT INTO all_questions VALUES (77,'Pension Investment Information','NULL',TRUE);
INSERT INTO all_questions VALUES (78,'Lifetime Retirement - Aged 55-64 years','NULL',FALSE);
INSERT INTO all_questions VALUES (79,'Lifetime Retirement - Aged 65-74 years','NULL',FALSE);
INSERT INTO all_questions VALUES (80,'Lifetime Retirement - Aged 75-84 years','NULL',FALSE);
INSERT INTO all_questions VALUES (81,'Lifetime Retirement - Aged 85+ years','NULL',FALSE);
INSERT INTO all_questions VALUES (82,'Lifetime Retirement - Leave as a legacy (inheritance)','NULL',FALSE);
INSERT INTO all_questions VALUES (83,'Information Sources','NULL',FALSE);
INSERT INTO all_questions VALUES (84,'Personal experience','Information Sources',TRUE);
INSERT INTO all_questions VALUES (85,'Advice from friends and family','Information Sources',TRUE);
INSERT INTO all_questions VALUES (86,'People in the media such as Martin Lewis','Information Sources',TRUE);
INSERT INTO all_questions VALUES (87,'Other investors on social media','Information Sources',TRUE);
INSERT INTO all_questions VALUES (88,'The government (e.g. Pensionwise)','Information Sources',TRUE);
INSERT INTO all_questions VALUES (89,'Professional financial advisers','Information Sources',TRUE);
INSERT INTO all_questions VALUES (90,'Information from pension product providers','Information Sources',TRUE);
INSERT INTO all_questions VALUES (91,'Investment Reasons','NULL',TRUE);
INSERT INTO all_questions VALUES (92,'Investment Prevention','NULL',TRUE);
INSERT INTO all_questions VALUES (93,'Knowledge Confidence','NULL',FALSE);
INSERT INTO all_questions VALUES (94,'Age to access pension','Knowledge Confidence',TRUE);
INSERT INTO all_questions VALUES (95,'Accessible amount','Knowledge Confidence',TRUE);
INSERT INTO all_questions VALUES (96,'Tax paid on pension','Knowledge Confidence',TRUE);
INSERT INTO all_questions VALUES (97,'Age to Access','NULL',TRUE);
INSERT INTO all_questions VALUES (98,'Proportion to Access','NULL',TRUE);
INSERT INTO all_questions VALUES (99,'Tax to Pay','NULL',TRUE);
INSERT INTO all_questions VALUES (100,'Understanding of Changes','NULL',FALSE);
INSERT INTO all_questions VALUES (101,'1 - Very poorly','Understanding of Changes',FALSE);
INSERT INTO all_questions VALUES (102,'2','Understanding of Changes',FALSE);
INSERT INTO all_questions VALUES (103,'3','Understanding of Changes',FALSE);
INSERT INTO all_questions VALUES (104,'4','Understanding of Changes',FALSE);
INSERT INTO all_questions VALUES (105,'5','Understanding of Changes',FALSE);
INSERT INTO all_questions VALUES (106,'6','Understanding of Changes',FALSE);
INSERT INTO all_questions VALUES (107,'7','Understanding of Changes',FALSE);
INSERT INTO all_questions VALUES (108,'8','Understanding of Changes',FALSE);
INSERT INTO all_questions VALUES (109,'9','Understanding of Changes',FALSE);
INSERT INTO all_questions VALUES (110,'10 - Very well','Understanding of Changes',FALSE);
INSERT INTO all_questions VALUES (111,'Revised Pension System','NULL',TRUE);
INSERT INTO all_questions VALUES (112,'Sentiment on Changes','NULL',FALSE);
INSERT INTO all_questions VALUES (113,'More choice','Sentiment on Changes',TRUE);
INSERT INTO all_questions VALUES (114,'More control','Sentiment on Changes',TRUE);
INSERT INTO all_questions VALUES (115,'Worried','Sentiment on Changes',TRUE);
INSERT INTO all_questions VALUES (116,'Investing Plans','NULL',TRUE);
INSERT INTO all_questions VALUES (117,'Changes to Pension System','NULL',FALSE);
INSERT INTO all_questions VALUES (118,'More/ better information & education','Changes to Pension System',TRUE);
INSERT INTO all_questions VALUES (119,'Increased trust in the system','Changes to Pension System',TRUE);
INSERT INTO all_questions VALUES (120,'Greater transparency around fees and charges','Changes to Pension System',TRUE);
INSERT INTO all_questions VALUES (121,'More/ better incentives (e.g. Tax breaks)','Changes to Pension System',TRUE);
INSERT INTO all_questions VALUES (122,'Information and Education Stakeholder','NULL',TRUE);
INSERT INTO all_questions VALUES (123,'Need Better Trust','NULL',TRUE);
INSERT INTO all_questions VALUES (124,'Better Incentives','NULL',TRUE);
INSERT INTO all_questions VALUES (125,'Planning Consideration','NULL',TRUE);
INSERT INTO all_questions VALUES (126,'Planning Process','NULL',FALSE);
INSERT INTO all_questions VALUES (127,'Talk to friends and family','Planning Process',TRUE);
INSERT INTO all_questions VALUES (128,'Talk to my partner','Planning Process',TRUE);
INSERT INTO all_questions VALUES (129,'Search online','Planning Process',TRUE);
INSERT INTO all_questions VALUES (130,'Search recommendations','Planning Process',TRUE);
INSERT INTO all_questions VALUES (131,'Traditional media','Planning Process',TRUE);
INSERT INTO all_questions VALUES (132,'Speak to a professional advisers','Planning Process',TRUE);
INSERT INTO all_questions VALUES (133,'Talk to a pension provider','Planning Process',TRUE);
INSERT INTO all_questions VALUES (134,'Flexibility','NULL',TRUE);
INSERT INTO all_questions VALUES (135,'Changing Needs','NULL',TRUE);
INSERT INTO all_questions VALUES (136,'Changing Needs Reason','NULL',TRUE);
INSERT INTO all_questions VALUES (137,'Lesser Need Reason','NULL',TRUE);
INSERT INTO all_questions VALUES (138,'Planning Pension Factors','NULL',FALSE);
INSERT INTO all_questions VALUES (139,'Lots of people like me invest in it','Planning Pension Factors',TRUE);
INSERT INTO all_questions VALUES (140,'Recommendation from friend','Planning Pension Factors',TRUE);
INSERT INTO all_questions VALUES (141,'Professional advice','Planning Pension Factors',TRUE);
INSERT INTO all_questions VALUES (142,'Make my own decisions','Planning Pension Factors',TRUE);
INSERT INTO all_questions VALUES (143,'How my financial circumstances may change in the future','Planning Pension Factors',TRUE);
INSERT INTO all_questions VALUES (144,'How Much to Invest','NULL',TRUE);
INSERT INTO all_questions VALUES (145,'Willingness to Risk','NULL',TRUE);
INSERT INTO all_questions VALUES (146,'Encouraging Factors','NULL',TRUE);
INSERT INTO all_questions VALUES (147,'Discouraging Factors','NULL',TRUE);
INSERT INTO all_questions VALUES (148,'New Ideas','NULL',FALSE);
INSERT INTO all_questions VALUES (149,'Later life annuity','New Ideas',TRUE);
INSERT INTO all_questions VALUES (150,'Online training programme','New Ideas',TRUE);
INSERT INTO all_questions VALUES (151,'Idiot guide','New Ideas',TRUE);
INSERT INTO all_questions VALUES (152,'Tripadvisor for pension','New Ideas',TRUE);
INSERT INTO all_questions VALUES (153,'Comparision side','New Ideas',TRUE);
INSERT INTO all_questions VALUES (154,'App to access pension','New Ideas',TRUE);
INSERT INTO all_questions VALUES (155,'Loyalty reward','New Ideas',TRUE);
INSERT INTO all_questions VALUES (156,'Life plan','New Ideas',TRUE);
INSERT INTO all_questions VALUES (157,'Jargon buster','New Ideas',TRUE);
INSERT INTO all_questions VALUES (158,'Flexibility','New Ideas',TRUE);
INSERT INTO all_questions VALUES (159,'Forum','New Ideas',TRUE);
SELECT * FROM all_questions;